### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: ShareIn - File Sharing app
email: pasupula1995@gmail.com
description: ShareIn is fast and secure file sharing app and its free to use app
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sharein.app/" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: Bhanupro212
github_username:  bhanup212
author: Bhanupro
logo: assets/images/large-logo.png
twitter:
  username: Bhanupro212
social:
  name: Bhanupro
  links:
    - https://twitter.com/Bhanupro212
    - https://www.linkedin.com/in/bhanupro
    - https://github.com/bhanup212

languages: ["en"]
ampdir: amp

github: https://github.com/sandoche/Mobile-app-landingpage-template

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
