name: ShareIn - Fast Files Share it
description: ShareIn-Files Sharing App!! It is the best sharing app to copy data, share all documents, shareit multiple files, and send files anywhere.

full_description: 'It is one of the best files sharing apps with over 1 Million + users downloaded worldwide. Gain complete control of sharing apps, media files, and documents. Face no complications when you share multiple files with one another. Select videos, photos, contacts, apps, and documents for your loved ones at lightning speed, even without an internet connection.<br>
<br>With a lot of features:
<br>- Secure file transfer – Easily share files from one phone to another
<br>- Fast, Uncompromising, and ultra-lightning speed with easy sharing!
<br>- Change storage path and use pip mode while transferring.
<br>- it supports sdcard as well as usb device
android: https://play.google.com/store/apps/details?id=com.sharein.filetransfer
screenshots:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  - 4.jpg
  - 5.jpg
  - 6.jpg
